// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keryrmjknawfgnrrdvdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcnlybWprbmF3ZmducnJkdmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDg5NTYsImV4cCI6MjA2MzEyNDk1Nn0.sjMh1BP4LarWOPOYi_9s2zxUqq2T6j1NvlBwN6K0hbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);